version: "3"
services:
    webclient-customer:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: webclient-customer
        image: webclient-customer:1.0
        restart: always
        volumes:
             - ./src:/app/src 
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - 3000:3000
        expose:
            - '3000'
        stdin_open: true